name: Test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Coverage
        uses: codecov/codecov-action@v2
        with:
          file: coverage.txt